// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshToken(ctx context.Context, refreshToken string) error
	GetRefreshToken(ctx context.Context, refreshToken string) (RefreshToken, error)
	GetUser(ctx context.Context, email string) (User, error)
	UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
