// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, refresh_token, expired_at
) VALUES (
             $1, $2, $3
         ) RETURNING id, user_id, refresh_token, expired_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiredAt    time.Time `json:"expired_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.RefreshToken, arg.ExpiredAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE refresh_token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, refreshToken)
	return err
}

const getRefreshTokenByEmail = `-- name: GetRefreshTokenByEmail :one
SELECT id, user_id, refresh_token, expired_at, created_at, updated_at FROM refresh_tokens
WHERE refresh_token = $1 and user_id = $2
LIMIT 1
`

type GetRefreshTokenByEmailParams struct {
	RefreshToken string `json:"refresh_token"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) GetRefreshTokenByEmail(ctx context.Context, arg GetRefreshTokenByEmailParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByEmail, arg.RefreshToken, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, refresh_token, expired_at)
VALUES ($1, $2, $3)
    ON CONFLICT (user_id)
DO UPDATE SET
    refresh_token = EXCLUDED.refresh_token,
           expired_at = EXCLUDED.expired_at
RETURNING id, user_id, refresh_token, expired_at, created_at, updated_at
`

type UpsertRefreshTokenParams struct {
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiredAt    time.Time `json:"expired_at"`
}

func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, upsertRefreshToken, arg.UserID, arg.RefreshToken, arg.ExpiredAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
