// Code generated by MockGen. DO NOT EDIT.
// Source: internal/util/token/maker.go

// Package mockmaker is a generated GoMock package.
package mockmaker

import (
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
	sqlc "github.com/hanifsyahsn/go_boilerplate/internal/db/sqlc"
)

// MockMaker is a mock of Maker interface.
type MockMaker struct {
	ctrl     *gomock.Controller
	recorder *MockMakerMockRecorder
}

// MockMakerMockRecorder is the mock recorder for MockMaker.
type MockMakerMockRecorder struct {
	mock *MockMaker
}

// NewMockMaker creates a new mock instance.
func NewMockMaker(ctrl *gomock.Controller) *MockMaker {
	mock := &MockMaker{ctrl: ctrl}
	mock.recorder = &MockMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaker) EXPECT() *MockMakerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockMaker) CreateToken(user sqlc.User, accessTokenDuration, RefreshTokenDuration time.Duration) (string, string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", user, accessTokenDuration, RefreshTokenDuration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockMakerMockRecorder) CreateToken(user, accessTokenDuration, RefreshTokenDuration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockMaker)(nil).CreateToken), user, accessTokenDuration, RefreshTokenDuration)
}

// RefreshToken mocks base method.
func (m *MockMaker) RefreshToken(email string, userId int64, accessTokenDuration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", email, userId, accessTokenDuration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockMakerMockRecorder) RefreshToken(email, userId, accessTokenDuration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockMaker)(nil).RefreshToken), email, userId, accessTokenDuration)
}

// VerifyToken mocks base method.
func (m *MockMaker) VerifyToken(tokenString string) (*jwt.Token, jwt.MapClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(jwt.MapClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockMakerMockRecorder) VerifyToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockMaker)(nil).VerifyToken), tokenString)
}
