// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/store.go

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sqlc "github.com/hanifsyahsn/go_boilerplate/internal/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockStore) CreateRefreshToken(ctx context.Context, arg sqlc.CreateRefreshTokenParams) (sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockStoreMockRecorder) CreateRefreshToken(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockStore)(nil).CreateRefreshToken), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// DeleteRefreshToken mocks base method.
func (m *MockStore) DeleteRefreshToken(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockStoreMockRecorder) DeleteRefreshToken(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockStore)(nil).DeleteRefreshToken), ctx, refreshToken)
}

// GetRefreshTokenByEmail mocks base method.
func (m *MockStore) GetRefreshTokenByEmail(ctx context.Context, arg sqlc.GetRefreshTokenByEmailParams) (sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByEmail", ctx, arg)
	ret0, _ := ret[0].(sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByEmail indicates an expected call of GetRefreshTokenByEmail.
func (mr *MockStoreMockRecorder) GetRefreshTokenByEmail(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByEmail", reflect.TypeOf((*MockStore)(nil).GetRefreshTokenByEmail), ctx, arg)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, email string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, email)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, email)
}

// RegisterTx mocks base method.
func (m *MockStore) RegisterTx(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTx", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RegisterTx indicates an expected call of RegisterTx.
func (mr *MockStoreMockRecorder) RegisterTx(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTx", reflect.TypeOf((*MockStore)(nil).RegisterTx), ctx, arg)
}

// UpsertRefreshToken mocks base method.
func (m *MockStore) UpsertRefreshToken(ctx context.Context, arg sqlc.UpsertRefreshTokenParams) (sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRefreshToken", ctx, arg)
	ret0, _ := ret[0].(sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRefreshToken indicates an expected call of UpsertRefreshToken.
func (mr *MockStoreMockRecorder) UpsertRefreshToken(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRefreshToken", reflect.TypeOf((*MockStore)(nil).UpsertRefreshToken), ctx, arg)
}
